/**
 * Central route registry for the storefront and admin shell.
 * No pages exist for these routes yet (Phase 1 builds no UI) — this
 * file exists so that later phases, and any component that needs to
 * link somewhere, reference one typed source of truth instead of
 * hard-coded path strings scattered across the codebase.
 */
export const ROUTES = {
  home: "/",
  collections: "/collections",
  collection: (slug: string) => `/collections/${slug}`,
  product: (slug: string) => `/products/${slug}`,
  newArrivals: "/new-arrivals",
  sale: "/sale",
  about: "/about",
  contact: "/contact",
  faqs: "/faqs",
  privacyPolicy: "/privacy-policy",
  termsConditions: "/terms-conditions",
  returnPolicy: "/returns",
  shippingPolicy: "/shipping",
  refundPolicy: "/refund-policy",
  maintenance: "/maintenance",
  orderConfirmation: "/order-confirmation",
  paymentSuccess: "/payment/success",
  paymentFailed: "/payment/failed",
  paymentPending: "/payment/pending",
  cart: "/cart",
  checkout: "/checkout",
  checkout: "/checkout",
  account: "/account",
  accountProfile: "/account/profile",
  accountAddresses: "/account/addresses",
  accountSettings: "/account/settings",
  wishlist: "/account/wishlist",
  orders: "/account/orders",
  orderDetail: (id: number | string) => `/account/orders/${id}`,
  login: "/login",
  register: "/register",
  admin: {
    root: "/admin",
    login: "/admin/login",
    products: "/admin/products",
    productNew: "/admin/products/new",
    productEdit: (id: number | string) => `/admin/products/${id}/edit`,
    categories: "/admin/categories",
    orders: "/admin/orders",
    orderDetail: (id: number | string) => `/admin/orders/${id}`,
    customers: "/admin/customers",
    customerDetail: (id: number | string) => `/admin/customers/${id}`,
    contentHomepage: "/admin/content/homepage",
    contentAbout: "/admin/content/about",
    contentHero: "/admin/content/hero",
    contentSlider: "/admin/content/slider",
    newArrivals: "/admin/new-arrivals",
    sale: "/admin/sale",
    settingsWebsite: "/admin/settings/website",
    settingsWhatsapp: "/admin/settings/whatsapp",
    settingsSeo: "/admin/settings/seo",
    newsletter: "/admin/newsletter",
  },
} as const;
